<?php
defined( 'ABSPATH' ) || exit;

get_header( 'shop' );

// Robust product object initialization following WooCommerce best practices
$product = null;

// First, try to get the global product object if it exists
if ( isset($GLOBALS['product']) && is_a($GLOBALS['product'], 'WC_Product') ) {
    $product = $GLOBALS['product'];
} else {
    // If global is not valid, initialize it properly
    $product_id = get_the_ID();
    
    // Validate we have a proper product ID and post type
    if ( $product_id && is_numeric($product_id) && get_post_type($product_id) === 'product' ) {
        $product = wc_get_product($product_id);
        
        // Validate the product object was created successfully
        if ( is_a($product, 'WC_Product') ) {
            $GLOBALS['product'] = $product;
        } else {
            error_log('ERROR: wc_get_product() failed for ID ' . $product_id . '. Returned: ' . print_r($product, true));
            $product = null;
        }
    } else {
        error_log('ERROR: Invalid product context. ID: ' . $product_id . ', Post type: ' . get_post_type($product_id));
    }
} ?>

<div class="page-shell">
    <section class="hero">
        <article class="gallery-card">
            <div class="badge-stack">
                <?php
                // Display product badges (sale, featured, etc.)
                $badges = array();
                
                // Only proceed with badge logic if we have a valid product object
                if ( $product && is_a($product, 'WC_Product') ) {
                    // Check if product is on sale
                    if ( $product->is_on_sale() ) {
                        $badges[] = array( 'text' => 'Limited Drop', 'type' => 'sale' );
                    }
                    
                    // Check if product is featured
                    if ( $product->is_featured() ) {
                        $badges[] = array( 'text' => 'Editors\' Pick', 'type' => 'featured' );
                    }
                } else {
                    error_log('WARNING: Cannot display product badges - invalid product object');
                }
                
                // Add more badge logic as needed
                
                if ( !empty($badges) ) {
                    foreach ( $badges as $badge ) {
                        echo '<span class="badge"><span class="dot"></span>' . esc_html($badge['text']) . '</span>';
                    }
                }
                ?>
            </div>
            <div class="main-image">
                <?php
                // Use the simplified gallery component that matches the concept design
                get_template_part( 'template-parts/components/product-gallery-simple' );
                ?>
            </div>
            <div class="thumb-strip">
                <!-- Thumbnails will be generated by WooCommerce gallery component -->
            </div>
        </article>

        <aside class="details-panel">
            <?php if ( $product && is_a($product, 'WC_Product') ) : ?>
                <!-- Collection Tag -->
                <span class="collection-tag">
                    <?php
                    // Get the first product category as collection tag
                    $terms = get_the_terms( $product->get_id(), 'product_cat' );
                    if ( $terms && !is_wp_error( $terms ) ) {
                        echo esc_html( $terms[0]->name );
                    } else {
                        echo 'AW25 Capsule';
                    }
                    ?>
                </span>
                
                <!-- Product Title -->
                <h1 class="product-title"><?php echo esc_html( $product->get_name() ); ?></h1>
                
                <!-- Product Subtitle/Description -->
                <?php if ( $product->get_short_description() ) : ?>
                    <div class="subtitle wc-short-description">
                        <?php
                        // Render WooCommerce short description allowing expected HTML instead of escaping tags
                        echo apply_filters( 'woocommerce_short_description', $product->get_short_description() );
                        ?>
                    </div>
                <?php endif; ?>

                <!-- Price Row -->
                <div class="price-row">
                    <?php woocommerce_template_single_price(); ?>
                </div>

                <!-- Options Block (Colors, Sizes, etc.) -->
                <div class="options-block">
                    <?php
                    // Product variations (colors, sizes, etc.)
                    if ( $product->is_type('variable') ) {
                        // Display variable product attributes in concept design style
                        $attributes = $product->get_variation_attributes();
                        $attribute_availability = array();

                        // Use WooCommerce standard pattern for variable products
                        $variation_ids = $product->get_children();
                        if ( ! empty( $variation_ids ) ) {
                            foreach ( $variation_ids as $variation_id ) {
                                $variation = wc_get_product( $variation_id );

                                if ( ! $variation || 'product_variation' !== $variation->get_type() ) {
                                    continue;
                                }

                                $variation_attributes = $variation->get_attributes();
                                if ( empty( $variation_attributes ) ) {
                                    continue;
                                }

                                $variation_in_stock = $variation->is_in_stock();
                                
                                // DEBUG: Add logging to understand what's happening with variations
                                if ( WP_DEBUG && WP_DEBUG_LOG ) {
                                    error_log( 'WooCommerce Variation Debug: ' . print_r( array(
                                        'variation_id' => $variation_id,
                                        'variation_in_stock' => $variation_in_stock,
                                        'variation_attributes' => $variation_attributes,
                                        'variation_stock_quantity' => $variation->get_stock_quantity(),
                                        'variation_manage_stock' => $variation->get_manage_stock()
                                    ), true ) );
                                }

                                foreach ( $variation_attributes as $variation_attribute_name => $variation_attribute_value ) {
                                    if ( '' === $variation_attribute_value ) {
                                        $variation_attribute_value = $variation->get_attribute( $variation_attribute_name );
                                    }

                                    if ( '' === $variation_attribute_value ) {
                                        continue;
                                    }

                                    $attribute_key = strpos( $variation_attribute_name, 'attribute_' ) === 0
                                        ? $variation_attribute_name
                                        : 'attribute_' . $variation_attribute_name;
                                    $attribute_value_slug = sanitize_title( $variation_attribute_value );

                                    if ( '' === $attribute_value_slug ) {
                                        continue;
                                    }

                                    if ( ! isset( $attribute_availability[ $attribute_key ] ) ) {
                                        $attribute_availability[ $attribute_key ] = array();
                                    }

                                    if ( ! isset( $attribute_availability[ $attribute_key ][ $attribute_value_slug ] ) ) {
                                        $attribute_availability[ $attribute_key ][ $attribute_value_slug ] = array(
                                            'has_variation' => true,
                                            'in_stock'      => true, // IMPROVED: Default to true for better UX
                                        );
                                    }

                                    // If this specific variation is out of stock, mark it as such
                                    if ( ! $variation_in_stock ) {
                                        $attribute_availability[ $attribute_key ][ $attribute_value_slug ]['in_stock'] = false;
                                    }
                                }
                            }
                        }

                        $default_attributes = $product->get_default_attributes();
                        if ( !empty($attributes) ) {
                            echo '<div class="variation-selects">';
                            foreach ( $attributes as $attribute_name => $attribute ) {
                                $attribute_label = wc_attribute_label( str_replace( 'attribute_', '', $attribute_name ), $product );
                                $attribute_base = str_replace( 'attribute_', '', $attribute_name );
                                $default_value = isset( $default_attributes[ $attribute_base ] ) ? sanitize_title( $default_attributes[ $attribute_base ] ) : '';
                                
                                echo '<div class="variation-select">';
                                echo '<span class="block-label">' . esc_html( $attribute_label ) . '</span>';
                                
                                // Get terms for this attribute
                                $terms = wp_get_post_terms( $product->get_id(), str_replace( 'attribute_', '', $attribute_name ) );
                                if ( $terms && !is_wp_error( $terms ) ) {
                                    if ( strpos( $attribute_name, 'color' ) !== false || strpos( $attribute_name, 'colour' ) !== false ) {
                                        // Color swatches
                                        echo '<div class="color-palette">';
                                        foreach ( $terms as $term ) {
                                            $term_slug   = sanitize_title( $term->slug );
                                            $color_code  = get_term_meta( $term->term_id, 'color_code', true );
                                            $availability = $attribute_availability[ $attribute_name ][ $term_slug ] ?? null;
                                            // IMPROVED: Proper stock calculation logic
                                            $is_in_stock  = isset( $availability['in_stock'] ) ? (bool) $availability['in_stock'] : true; // Default to true for better UX
                                            $is_default   = ( '' !== $default_value && $default_value === $term_slug );
                                            $initial_selected = $is_default && $is_in_stock;
                                            $button_classes = array( 'swatch', 'color-variant' );
                                            if ( $initial_selected ) {
                                                $button_classes[] = 'selected';
                                            }
                                            if ( ! $is_in_stock ) {
                                                $button_classes[] = 'disabled';
                                                $button_classes[] = 'out-of-stock';
                                            }

                                            $button_attributes = sprintf(
                                                'class="%1$s" type="button" data-attribute="%2$s" data-value="%3$s" aria-disabled="%4$s" data-default="%5$s" aria-pressed="%6$s" data-in-stock="%7$s" data-attribute-name="%2$s" data-term-slug="%3$s"',
                                                esc_attr( implode( ' ', $button_classes ) ),
                                                esc_attr( $attribute_name ),
                                                esc_attr( $term_slug ),
                                                $is_in_stock ? 'false' : 'true',
                                                $is_default ? 'true' : 'false',
                                                $initial_selected ? 'true' : 'false',
                                                $is_in_stock ? 'true' : 'false'
                                            );

                                            echo '<button ' . $button_attributes . '>';
                                            if ( $color_code ) {
                                                echo '<span class="tone" style="background: ' . esc_attr( $color_code ) . ';"></span>';
                                            }
                                            echo '<span class="swatch-name">' . esc_html( $term->name ) . '</span>';
                                            echo '</button>';
                                        }
                                        echo '</div>';
                                    } else {
                                        // Size or other select
                                        echo '<div class="size-grid">';
                                        foreach ( $terms as $term ) {
                                            $term_slug    = sanitize_title( $term->slug );
                                            $availability = $attribute_availability[ $attribute_name ][ $term_slug ] ?? null;
                                            // IMPROVED: Proper stock calculation logic
                                            $is_in_stock  = isset( $availability['in_stock'] ) ? (bool) $availability['in_stock'] : true; // Default to true for better UX
                                            $is_default   = ( '' !== $default_value && $default_value === $term_slug );
                                            $initial_selected = $is_default && $is_in_stock;
                                            $button_classes = array( 'size-tile', 'size-selection__button' );
                                            if ( $initial_selected ) {
                                                $button_classes[] = 'selected';
                                            }
                                            if ( ! $is_in_stock ) {
                                                $button_classes[] = 'disabled';
                                                $button_classes[] = 'is-out-of-stock';
                                            }

                                            $button_attributes = sprintf(
                                                'class="%1$s" type="button" data-attribute="%2$s" data-value="%3$s" aria-disabled="%4$s" data-default="%5$s" aria-pressed="%6$s" data-in-stock="%7$s" data-attribute-name="%2$s" data-term-slug="%3$s"',
                                                esc_attr( implode( ' ', $button_classes ) ),
                                                esc_attr( $attribute_name ),
                                                esc_attr( $term_slug ),
                                                $is_in_stock ? 'false' : 'true',
                                                $is_default ? 'true' : 'false',
                                                $initial_selected ? 'true' : 'false',
                                                $is_in_stock ? 'true' : 'false'
                                            );

                                            echo '<button ' . $button_attributes . '>' . esc_html( $term->name ) . '</button>';
                                        }
                                        echo '</div>';
                                    }
                                }
                                echo '</div>';
                            }
                            echo '</div>';
                        }

                        // Stock availability for variable products
                        if ( $product->get_manage_stock() ) {
                            echo '<div class="availability">';
                            echo '<span class="stock-badge">In Stock</span>';
                            echo '<span class="stock-copy">Available in multiple sizes</span>';
                            echo '</div>';
                        }

                        // Custom variation form for better UX while maintaining WooCommerce functionality
                        echo '<div class="variable-add-to-cart">';
                        echo '<form class="variations_form cart eshop-variations-form" action="' . esc_url( apply_filters( 'woocommerce_add_to_cart_form_action', $product->get_permalink() ) ) . '" method="post" enctype="multipart/form-data" data-product_id="' . absint( $product->get_id() ) . '">';
                        
                        // Hidden selects for WooCommerce compatibility
                        foreach ( $attributes as $attribute_name => $options ) {
                            $attr_key = (strpos($attribute_name, 'attribute_') === 0) ? $attribute_name : 'attribute_' . $attribute_name;
                            $taxonomy = str_replace('attribute_', '', $attribute_name);
                            
                            echo '<select name="' . esc_attr( $attr_key ) . '" id="' . esc_attr( sanitize_title( $attr_key ) ) . '" class="hidden" data-attribute_name="' . esc_attr( $attr_key ) . '" style="display: none;">';
                            echo '<option value="">' . esc_html__( 'Choose an option', 'woocommerce' ) . '</option>';
                            
                            if ( ! empty( $options ) ) {
                                if ( taxonomy_exists( $taxonomy ) ) {
                                    $terms = wc_get_product_terms( $product->get_id(), $taxonomy, array( 'fields' => 'all' ) );
                                    foreach ( $terms as $term ) {
                                        if ( in_array( $term->slug, $options, true ) ) {
                                            echo '<option value="' . esc_attr( $term->slug ) . '">' . esc_html( $term->name ) . '</option>';
                                        }
                                    }
                                } else {
                                    foreach ( $options as $option ) {
                                        echo '<option value="' . esc_attr( $option ) . '">' . esc_html( $option ) . '</option>';
                                    }
                                }
                            }
                            echo '</select>';
                        }
                        
                        // Add hidden product_id field
                        echo '<input type="hidden" name="add-to-cart" value="' . esc_attr( $product->get_id() ) . '" />';
                        
                        // Add quantity field (WooCommerce will style this)
                        echo '<div class="single_variation_wrap" style="display: none;">';
                        echo '    <div class="woocommerce-variation single_variation" style="display: block;"></div>';
                        echo '    <div class="woocommerce-variation-add-to-cart variations_button">';
                        echo '        <div class="quantity">';
                        echo '            <label class="screen-reader-text" for="quantity_' . esc_attr( $product->get_id() ) . '">' . esc_html__( 'Quantity', 'woocommerce' ) . '</label>';
                        echo '            <input type="number" id="quantity_' . esc_attr( $product->get_id() ) . '" class="input-text qty text" name="quantity" value="1" min="1" max="999" step="1" inputmode="numeric" />';
                        echo '        </div>';
                        echo '        <button type="submit" class="single_add_to_cart_button button alt disabled wc-variation-selection-needed">' . esc_html__( 'Add to cart', 'woocommerce' ) . '</button>';
                        echo '        <input type="hidden" name="variation_id" value="" />';
                        echo '    </div>';
                        echo '</div>';
                        
                        echo '</form>';
                        echo '</div>';
                    }
                    
                    // Simple product add to cart
                    if ( $product->is_type('simple') ) {
                        echo '<div class="simple-add-to-cart">';
                        woocommerce_simple_add_to_cart();
                        echo '</div>';
                    }
                    ?>
                </div>

                <!-- CTA Row intentionally removed to prevent duplicate quantity/add-to-cart blocks.
                     Wishlist buttons are included inside the add-to-cart templates
                     (simple.php and variation-add-to-cart-button.php). -->

                <!-- Note Banner -->
                <div class="note-banner">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M12 8v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z" />
                    </svg>
                    Ships within 48 hours from Athens with carbon-neutral delivery.
                </div>

                <!-- Detail Accordions -->
                <div class="detail-accordions">
                    <div class="detail-accordion">
                        <button class="detail-accordion-trigger" type="button" aria-expanded="true">
                            <span>Shipping & Returns</span>
                            <span class="icon" aria-hidden="true">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M6 9l6 6 6-6"></path>
                                </svg>
                            </span>
                        </button>
                        <div class="detail-accordion-panel">
                            <p>Complimentary carbon-neutral delivery across Greece within 2 business days. EU orders arrive in 3–5 days.</p>
                            <p>We offer free exchanges within 30 days. Returns remain effortless—use the enclosed prepaid label or visit a Walking Company boutique.</p>
                        </div>
                    </div>

                    <div class="detail-accordion">
                        <button class="detail-accordion-trigger" type="button" aria-expanded="false">
                            <span>Payment Options</span>
                            <span class="icon" aria-hidden="true">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M6 9l6 6 6-6"></path>
                                </svg>
                            </span>
                        </button>
                        <div class="detail-accordion-panel" hidden>
                            <p>Secure checkout supports Visa, Mastercard, Amex, and Apple Pay. Klarna instalments are available for purchases above €180.</p>
                            <p>Your card is only charged once the pair leaves our atelier.</p>
                        </div>
                    </div>
                </div>
            <?php else : ?>
                <div class="error-message">
                    <p><?php _e('Product information is currently unavailable. Please try again later.', 'eshop-theme'); ?></p>
                </div>
            <?php endif; ?>
        </aside>
    </section>

    <?php
        /**
         * Hook: woocommerce_after_single_product_summary.
         *
         * @hooked woocommerce_output_product_data_tabs - 10
         * @hooked woocommerce_upsell_display - 15
         * @hooked woocommerce_output_related_products - 20
         */
        do_action( 'woocommerce_after_single_product_summary' );
    ?>
</div>

<!-- Accordion JavaScript -->
<script>
document.addEventListener('DOMContentLoaded', function () {
    const triggers = document.querySelectorAll('.detail-accordion-trigger');

    triggers.forEach(function (trigger) {
        trigger.addEventListener('click', function () {
            const expanded = trigger.getAttribute('aria-expanded') === 'true';
            const panel = trigger.nextElementSibling;

            trigger.setAttribute('aria-expanded', String(!expanded));

            if (panel) {
                if (expanded) {
                    panel.setAttribute('hidden', '');
                } else {
                    panel.removeAttribute('hidden');
                }
            }
        });
    });
});
</script>

<?php get_footer( 'shop' );