<?php
defined( 'ABSPATH' ) || exit;

get_header( 'shop' );

// Ensure we have the global product object set
if ( ! is_product() ) {
    $product_id = get_the_ID();
    if ( $product_id && get_post_type( $product_id ) === 'product' ) {
        $GLOBALS['product'] = wc_get_product( $product_id );
    }
} ?>

<div class="page-shell">
    <section class="hero">
        <article class="gallery-card">
            <div class="badge-stack">
                <!-- Badges can be dynamically added here -->
            </div>
            <div class="main-image">
                <?php
                // Use the custom product image template which has better error handling
                get_template_part( 'woocommerce/single-product/product-image' );
                ?>
            </div>
            <div class="thumb-strip">
                <!-- Thumbnails will be generated by WooCommerce gallery -->
            </div>
        </article>

        <aside class="details-panel">
            <?php
                /**
                 * Hook: woocommerce_single_product_summary.
                 *
                 * @hooked woocommerce_template_single_title - 5
                 * @hooked woocommerce_template_single_rating - 10
                 * @hooked woocommerce_template_single_price - 10
                 * @hooked woocommerce_template_single_excerpt - 20
                 * @hooked woocommerce_template_single_add_to_cart - 30
                 * @hooked woocommerce_template_single_meta - 40
                 * @hooked woocommerce_template_single_sharing - 50
                 * @hooked WC_Structured_Data::generate_product_data() - 60
                 */
                do_action( 'woocommerce_single_product_summary' );
            ?>
        </aside>
    </section>

    <?php
        /**
         * Hook: woocommerce_after_single_product_summary.
         *
         * @hooked woocommerce_output_product_data_tabs - 10
         * @hooked woocommerce_upsell_display - 15
         * @hooked woocommerce_output_related_products - 20
         */
        do_action( 'woocommerce_after_single_product_summary' );
    ?>
</div>

<?php get_footer( 'shop' );