<?php
defined( 'ABSPATH' ) || exit;

get_header( 'shop' );

// Ensure we have the global product object set
if ( ! is_product() ) {
    $product_id = get_the_ID();
    if ( $product_id && get_post_type( $product_id ) === 'product' ) {
        $GLOBALS['product'] = wc_get_product( $product_id );
    }
} ?>

<div class="page-shell">
    <section class="hero">
        <article class="gallery-card">
            <div class="badge-stack">
                <?php
                // Display product badges (sale, featured, etc.)
                $badges = array();
                
                // Check if product is on sale
                if ( isset($GLOBALS['product']) && $GLOBALS['product']->is_on_sale() ) {
                    $badges[] = array( 'text' => 'Limited Drop', 'type' => 'sale' );
                }
                
                // Check if product is featured
                if ( isset($GLOBALS['product']) && $GLOBALS['product']->is_featured() ) {
                    $badges[] = array( 'text' => 'Editors\' Pick', 'type' => 'featured' );
                }
                
                // Add more badge logic as needed
                
                if ( !empty($badges) ) {
                    foreach ( $badges as $badge ) {
                        echo '<span class="badge"><span class="dot"></span>' . esc_html($badge['text']) . '</span>';
                    }
                }
                ?>
            </div>
            <div class="main-image">
                <?php
                // Use the custom product image template which has better error handling
                get_template_part( 'woocommerce/single-product/product-image' );
                ?>
            </div>
            <div class="thumb-strip">
                <!-- Thumbnails will be generated by WooCommerce gallery component -->
            </div>
        </article>

        <aside class="details-panel">
            <?php
            // Get the product for our custom rendering
            $product = isset($GLOBALS['product']) ? $GLOBALS['product'] : null;
            
            if ( $product ) :
            ?>
                <!-- Collection Tag -->
                <span class="collection-tag">
                    <?php
                    // Get the first product category as collection tag
                    $terms = get_the_terms( $product->get_id(), 'product_cat' );
                    if ( $terms && !is_wp_error( $terms ) ) {
                        echo esc_html( $terms[0]->name );
                    } else {
                        echo 'AW25 Capsule';
                    }
                    ?>
                </span>
                
                <!-- Product Title -->
                <h1 class="product-title"><?php echo esc_html( $product->get_name() ); ?></h1>
                
                <!-- Product Subtitle/Description -->
                <?php if ( $product->get_short_description() ) : ?>
                    <p class="subtitle"><?php echo esc_html( $product->get_short_description() ); ?></p>
                <?php endif; ?>

                <!-- Price Row -->
                <div class="price-row">
                    <?php woocommerce_template_single_price(); ?>
                </div>

                <!-- Options Block (Colors, Sizes, etc.) -->
                <div class="options-block">
                    <?php
                    // Product variations (colors, sizes, etc.)
                    if ( $product->is_type('variable') ) {
                        woocommerce_single_variation_add_to_cart_button();
                    }
                    
                    // Simple product add to cart
                    if ( $product->is_type('simple') ) {
                        woocommerce_simple_add_to_cart();
                    }
                    ?>
                </div>

                <!-- CTA Row -->
                <div class="cta-row">
                    <?php woocommerce_template_single_add_to_cart(); ?>
                    
                    <!-- Wishlist Button -->
                    <button class="wishlist" aria-label="Add to wishlist" data-product-id="<?php echo esc_attr($product->get_id()); ?>">
                        ♡
                    </button>
                </div>

                <!-- Note Banner -->
                <div class="note-banner">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M12 8v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z" />
                    </svg>
                    Ships within 48 hours from Athens with carbon-neutral delivery.
                </div>

                <!-- Detail Accordions -->
                <div class="detail-accordions">
                    <div class="detail-accordion">
                        <button class="detail-accordion-trigger" type="button" aria-expanded="true">
                            <span>Shipping & Returns</span>
                            <span class="icon" aria-hidden="true">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M6 9l6 6 6-6"></path>
                                </svg>
                            </span>
                        </button>
                        <div class="detail-accordion-panel">
                            <p>Complimentary carbon-neutral delivery across Greece within 2 business days. EU orders arrive in 3–5 days.</p>
                            <p>We offer free exchanges within 30 days. Returns remain effortless—use the enclosed prepaid label or visit a Walking Company boutique.</p>
                        </div>
                    </div>

                    <div class="detail-accordion">
                        <button class="detail-accordion-trigger" type="button" aria-expanded="false">
                            <span>Payment Options</span>
                            <span class="icon" aria-hidden="true">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M6 9l6 6 6-6"></path>
                                </svg>
                            </span>
                        </button>
                        <div class="detail-accordion-panel" hidden>
                            <p>Secure checkout supports Visa, Mastercard, Amex, and Apple Pay. Klarna instalments are available for purchases above €180.</p>
                            <p>Your card is only charged once the pair leaves our atelier.</p>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </aside>
    </section>

    <?php
        /**
         * Hook: woocommerce_after_single_product_summary.
         *
         * @hooked woocommerce_output_product_data_tabs - 10
         * @hooked woocommerce_upsell_display - 15
         * @hooked woocommerce_output_related_products - 20
         */
        do_action( 'woocommerce_after_single_product_summary' );
    ?>
</div>

<!-- Accordion JavaScript -->
<script>
document.addEventListener('DOMContentLoaded', function () {
    const triggers = document.querySelectorAll('.detail-accordion-trigger');

    triggers.forEach(function (trigger) {
        trigger.addEventListener('click', function () {
            const expanded = trigger.getAttribute('aria-expanded') === 'true';
            const panel = trigger.nextElementSibling;

            trigger.setAttribute('aria-expanded', String(!expanded));

            if (panel) {
                if (expanded) {
                    panel.setAttribute('hidden', '');
                } else {
                    panel.removeAttribute('hidden');
                }
            }
        });
    });
});
</script>

<?php get_footer( 'shop' );