<?php
/**
 * Product Card Component (Grid) - CORRECTED VERSION
 * This file no longer calls wc_product_class()
 */
defined( 'ABSPATH' ) || exit;

global $product;
if ( empty( $product ) || ! $product->is_visible() ) {
    return;
}

$product_id = $product->get_id();
$is_on_sale = $product->is_on_sale();
$is_variable = $product->is_type('variable');
$date_created = get_the_date('c', $product_id);

// Get product colors from WooCommerce attributes (fallback if no ACF)
$product_colors = array();
$color_attribute = wc_get_attribute_taxonomy('pa_color');
if ($color_attribute && taxonomy_exists('pa_color')) {
    $color_terms = wp_get_post_terms($product_id, 'pa_color');
    foreach ($color_terms as $term) {
        $color_data = get_term_meta($term->term_id, 'pa_color_color', true);
        if (!$color_data) {
            // Fallback color based on term name if no color data is set
            $color_data = eshop_get_color_from_name($term->name);
        }
        if ($color_data) {
            $product_colors[] = array(
                'name' => $term->name,
                'hex' => $color_data
            );
        }
    }
}

// If no colors found from attributes, use default colors
if (empty($product_colors)) {
    $product_colors = array(
        array('name' => 'Pink', 'hex' => '#f8c5d8'),
        array('name' => 'Rose', 'hex' => '#ee81b3'),
        array('name' => 'Neutral', 'hex' => '#ffe6f0'),
        array('name' => 'Dark', 'hex' => '#252536')
    );
}

// Get variation stock info
$stock_info = array();
if ($is_variable) {
    $variations = $product->get_available_variations();
    foreach ($variations as $variation) {
        $attributes = $variation['attributes'];
        $stock_quantity = $variation['stock_quantity'];
        $size = isset($attributes['attribute_pa_size']) ? $attributes['attribute_pa_size'] : '';
        if ($size) {
            $stock_info[$size] = array(
                'stock' => $stock_quantity,
                'status' => $stock_quantity > 5 ? 'available' : ($stock_quantity > 0 ? 'low' : 'out')
            );
        }
    }
}
?>
<article class="product-card"
         data-product-id="<?php echo esc_attr($product_id); ?>"
         data-variable="<?php echo $is_variable ? 'true' : 'false'; ?>"
         data-wishlist="true"
         data-date-added="<?php echo esc_attr($date_created); ?>"
         data-sale-price="<?php echo $product->get_sale_price(); ?>"
         data-regular-price="<?php echo $product->get_regular_price(); ?>">
    <div class="product-card__media">
        <a href="<?php echo esc_url( get_permalink() ); ?>">
            <?php echo woocommerce_get_product_thumbnail(); ?>
        </a>
        <div class="badge-stack">
            <?php if ($is_on_sale) : ?>
                <?php
                $regular_price = $product->get_regular_price();
                $sale_price = $product->get_sale_price();
                if ($regular_price && $sale_price) {
                    $percentage = round((($regular_price - $sale_price) / $regular_price) * 100);
                    echo '<span class="badge badge--sale">' . $percentage . '% Off</span>';
                } else {
                    echo apply_filters( 'woocommerce_sale_flash', '<span class="badge badge--sale">' . esc_html__( 'Sale!', 'woocommerce' ) . '</span>', $post, $product );
                }
                ?>
            <?php endif; ?>
            <?php
            // Add "New" badge for products created within last 30 days
            $date_created_timestamp = strtotime($date_created);
            $thirty_days_ago = strtotime('-30 days');
            if ($date_created_timestamp > $thirty_days_ago) {
                echo '<span class="badge">New</span>';
            }
            ?>
        </div>
        <button class="wishlist-button"
                type="button"
                aria-label="Add to wishlist"
                data-product-id="<?php echo esc_attr($product_id); ?>">♡</button>
        <div class="media-dot-row" aria-hidden="true">
            <!-- Media dots will be generated by JavaScript -->
        </div>
        <div class="size-overlay" aria-hidden="true">
            <!-- Size chips can be dynamically generated here -->
        </div>
    </div>
    <div class="product-card__info">
        <h2 class="product-card__title">
            <a href="<?php echo esc_url( get_permalink() ); ?>"><?php echo esc_html( $product->get_name() ); ?></a>
        </h2>
        <span class="product-card__sku"><?php echo ( $sku = $product->get_sku() ) ? 'SKU: ' . esc_html( $sku ) : '&nbsp;'; ?></span>
        <div class="category-line">
            <?php
            $categories = wc_get_product_category_list( $product_id, ', ', '', '' );
            if ($categories) {
                echo $categories;
            }
            ?>
        </div>
        <div class="color-row">
            <?php if (!empty($product_colors)) : ?>
                <span>Palette</span>
                <div class="color-dots" aria-hidden="true">
                    <?php foreach ($product_colors as $color) : ?>
                        <span class="color-dot"
                              data-color="<?php echo esc_attr($color['name']); ?>"
                              style="background: <?php echo esc_attr($color['hex']); ?>"
                              title="<?php echo esc_attr($color['name']); ?>"></span>
                    <?php endforeach; ?>
                </div>
            <?php else : ?>
                <span>Colors Available</span>
                <div class="color-dots" aria-hidden="true">
                    <span class="color-dot" style="background: linear-gradient(135deg, #f8c5d8 0%, #ee81b3 100%);"></span>
                    <span class="color-dot" style="background: #ffe6f0;"></span>
                    <span class="color-dot" style="background: #252536;"></span>
                </div>
            <?php endif; ?>
        </div>
        <div class="price-row">
            <?php
            echo $product->get_price_html();
            if ($product->is_in_stock() && $product->get_stock_quantity() < 5 && $product->get_stock_quantity() > 0) :
            ?>
                <span class="stock-flag">Low stock</span>
            <?php endif; ?>
        </div>
    </div>
    <div class="card-footer">
        <?php
        $button_class = 'add-to-cart';
        if ($is_variable) {
            $button_class .= ' variable-product';
        }
        woocommerce_template_loop_add_to_cart(array('class' => $button_class));
        ?>
    </div>
</article>